### ISSUE TITLE
Failed to build kernel with proxmox-kernel-6.17.2 and pivccu-modules-dkms

### ISSUE THREAD

**Issue by walburgf** [alexreinert/piVCCU#559]
make.log shows the following errors:

hb_rf_usb.c: In function ‘hb_rf_usb_probe’:
hb_rf_usb.c:559:16: error: assignment to ‘int (*)(struct gpio_chip *, unsigned int,  int)’ from incompatible pointer type ‘void (*)(struct gpio_chip *, unsigned int,  int)’ [-Wincompatible-pointer-types]
  559 |   port->gc.set = hb_rf_usb_gpio_set;
      |                ^
hb_rf_usb.c:563:25: error: assignment to ‘int (*)(struct gpio_chip *, long unsigned int *, long unsigned int *)’ from incompatible pointer type ‘void (*)(struct gpio_chip *, long unsigned int *, long unsigned int *)’ [-Wincompatible-pointer-types]
  563 |   port->gc.set_multiple = hb_rf_usb_gpio_set_multiple;
      |                         ^
make[4]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: hb_rf_usb.o] Error 1
make[4]: *** Waiting for unfinished jobs....
hb_rf_usb_2.c: In function ‘hb_rf_usb_2_probe’:
hb_rf_usb_2.c:580:18: error: assignment to ‘int (*)(struct gpio_chip *, unsigned int,  int)’ from incompatible pointer type ‘void (*)(struct gpio_chip *, unsigned int,  int)’ [-Wincompatible-pointer-types]
  580 |     port->gc.set = hb_rf_usb_2_gpio_set;
      |                  ^
hb_rf_usb_2.c:584:27: error: assignment to ‘int (*)(struct gpio_chip *, long unsigned int *, long unsigned int *)’ from incompatible pointer type ‘void (*)(struct gpio_chip *, long unsigned int *, long unsigned int *)’ [-Wincompatible-pointer-types]
  584 |     port->gc.set_multiple = hb_rf_usb_2_gpio_set_multiple;
      |                           ^
make[4]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: hb_rf_usb_2.o] Error 1
generic_raw_uart.c:828:5: warning: no previous prototype for ‘generic_raw_uart_get_gpio_index’ [-Wmissing-prototypes]
  828 | int generic_raw_uart_get_gpio_index(struct device *dev, char *con_id, unsigned int idx)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generic_raw_uart.c:843:5: warning: no previous prototype for ‘generic_raw_uart_get_led_gpio_index’ [-Wmissing-prototypes]
  843 | int generic_raw_uart_get_led_gpio_index(struct generic_raw_uart_instance *instance, struct device *dev, enum generic_raw_uart_led led)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generic_raw_uart.c:975:5: warning: no previous prototype for ‘generic_raw_uart_probe_rtc_device’ [-Wmissing-prototypes]
  975 | int generic_raw_uart_probe_rtc_device(struct device *dev, bool *rtc_detected)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hb_rf_eth.c: In function ‘hb_rf_eth_init’:
hb_rf_eth.c:752:10: error: assignment to ‘int (*)(struct gpio_chip *, unsigned int,  int)’ from incompatible pointer type ‘void (*)(struct gpio_chip *, unsigned int,  int)’ [-Wincompatible-pointer-types]
  752 |   gc.set = hb_rf_eth_gpio_set;
      |          ^
hb_rf_eth.c:756:19: error: assignment to ‘int (*)(struct gpio_chip *, long unsigned int *, long unsigned int *)’ from incompatible pointer type ‘void (*)(struct gpio_chip *, long unsigned int *, long unsigned int *)’ [-Wincompatible-pointer-types]
  756 |   gc.set_multiple = hb_rf_eth_gpio_set_multiple;
      |                   ^
make[4]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: hb_rf_eth.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/Makefile:2016: .] Error 2
make[2]: *** [/usr/src/linux-headers-6.17.2-2-pve/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/pivccu/1.0.85/build'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.17.2-2-pve'
make: *** [Makefile:30: all] Error 2

**Comment by df8oe** [comment]
Modules do not build on kernel 6.18.1 - same error messages in logs.
