### ISSUE TITLE
DKMS issues on openhabianpi: kernel v4.4 vs v3.6?

### ISSUE THREAD

**Issue by uqs** [alexreinert/piVCCU#117]
Hey there, I'm trying to get HmIP devices to work (in addition to Homematic devices), so I need to switch from homegear to piVCCU and am following the instructions here: https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md

The kernel module compilation is failing though. Why does pivccu-modules-dkms hard-depend on the 3.6 kernel and can't just depend on the latest?

```
# uname -a
Linux openHABianPi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
```

```
# apt install pivccu-modules-dkms
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  cpp-4.6 dkms gcc-4.6 linux-headers-3.6-trunk-common linux-headers-3.6-trunk-rpi linux-kbuild-3.6
Suggested packages:
  gcc-4.6-locales python3-apport menu libmudflap0-4.6-dev gcc-4.6-doc libgcc1-dbg libgomp1-dbg libquadmath-dbg libmudflap0-dbg libcloog-ppl1 | libcloog-ppl0
  libppl-c4 libppl12 | libppl9 binutils-gold
The following NEW packages will be installed:
  cpp-4.6 dkms gcc-4.6 linux-headers-3.6-trunk-common linux-headers-3.6-trunk-rpi linux-kbuild-3.6 pivccu-modules-dkms
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
...
```

```
Setting up pivccu-modules-dkms (1.0.21) ...
Loading new pivccu-1.0.21 DKMS files...
It is likely that 4.14.79-v7+ belongs to a chroot's host
Building for 3.6-trunk-rpi, 4.14.79+, 4.14.79-v7+, 4.4.0-1-rpi and 4.4.0-1-rpi2
Building initial module for 3.6-trunk-rpi
Error! Bad return status for module build on kernel: 3.6-trunk-rpi (armv7l)
Consult /var/lib/dkms/pivccu/1.0.21/build/make.log for more information.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Setting up gcc-4.6 (4.6.4-5+rpi1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up linux-kbuild-3.6 (3.6-1~experimental.1+rpi2+b2) ...
Setting up linux-headers-3.6-trunk-rpi (3.6.9-1~experimental.1+rpi7) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 3.6-trunk-rpi
Error! Bad return status for module build on kernel: 3.6-trunk-rpi (armv7l)
Consult /var/lib/dkms/pivccu/1.0.21/build/make.log for more information.
```

and that log has:
```
# cat /var/lib/dkms/pivccu/1.0.21/build/make.log
DKMS make.log for pivccu-1.0.21 for kernel 3.6-trunk-rpi (armv7l)
Sun Jan 20 21:37:42 CET 2019
make -C /lib/modules/3.6-trunk-rpi/build M=/var/lib/dkms/pivccu/1.0.21/build modules
make[1]: Entering directory '/usr/src/linux-headers-3.6-trunk-rpi'
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
  CC [M]  /var/lib/dkms/pivccu/1.0.21/build/eq3_char_loop.o
  CC [M]  /var/lib/dkms/pivccu/1.0.21/build/plat_eq3ccu2.o
  CC [M]  /var/lib/dkms/pivccu/1.0.21/build/generic_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.21/build/pl011_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.21/build/dw_apb_raw_uart.o
/var/lib/dkms/pivccu/1.0.21/build/generic_raw_uart.c:40:33: fatal error: linux/gpio/consumer.h: No such file or directory
compilation terminated.
/var/lib/dkms/pivccu/1.0.21/build/dw_apb_raw_uart.c:28:25: fatal error: linux/reset.h: No such file or directory
compilation terminated.
  CC [M]  /var/lib/dkms/pivccu/1.0.21/build/meson_raw_uart.o
/var/lib/dkms/pivccu/1.0.21/build/meson_raw_uart.c:34:25: fatal error: linux/reset.h: No such file or directory
compilation terminated.
/usr/src/linux-headers-3.6-trunk-common/scripts/Makefile.build:313: recipe for target '/var/lib/dkms/pivccu/1.0.21/build/dw_apb_raw_uart.o' failed

```

help? How can I tell dkms to skip 3.6 and where do I even get the headers/sources for 4.14.79-v7+ ?

**Comment by alexreinert** [comment]
It does not hard depend on 3.6. Instead DKMS builds the kernel modules for all kernel headers it finds in the directory /usr/src

So just remove old and unused kernel headers in that directory and run
```dpkg-reconfigure pivccu-modules-dkms```

**Comment by uqs** [comment]
Sure, first I followed https://github.com/raspberrypi/firmware/issues/63 to get the headers for my version installed. 

Then I could swear that I tried to 'apt remove' the 3.6 headers and that would've caused pivccu-modules-dkms to also get removed, so I didn't (or did I try to remove kbuild-3.6?).

Anyway, deinstalling the other headers now worked w/o collateral damage and DKMS ran to completion just fine.

Weird. Sorry for the noise!
