### ISSUE TITLE
pivccu-modules-dkms build failed - Error! Bad return status for module build on kernel: 4.9.35-v7+ (armv7l)

### ISSUE THREAD

**Issue by zioalex** [alexreinert/piVCCU#185]
HI dear maintainers,
I am having trouble making piVCCU up and running.
I followed the setup guide https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md but the procdedure fails.

I searched around and found the ticket https://github.com/alexreinert/piVCCU/issues/130.
The i tried to reinstall the packages  raspberrypi-kernel-headers pivccu-modules-dkms but it didn't help.
```

root@raspberrypi:~# apt install raspberrypi-kernel-headers pivccu-modules-dkms --reinstall
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 2 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/15.3 MB of archives.
After this operation, 0 B of additional disk space will be used.
Preconfiguring packages ...
(Reading database ... 234407 files and directories currently installed.)
Preparing to unpack .../pivccu-modules-dkms_1.0.36_all.deb ...

------------------------------
Deleting module version: 1.0.36
completely from the DKMS tree.
------------------------------
Done.
Unpacking pivccu-modules-dkms (1.0.36) over (1.0.36) ...
Preparing to unpack .../raspberrypi-kernel-headers_1.20170703-1_armhf.deb ...
Unpacking raspberrypi-kernel-headers (1.20170703-1) over (1.20170703-1) ...
Setting up pivccu-modules-dkms (1.0.36) ...

Creating symlink /var/lib/dkms/pivccu/1.0.36/source ->
                 /usr/src/pivccu-1.0.36

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=4.9.35-v7+ ARCH=arm all......(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.9.35-v7+ (armv7l)
Consult /var/lib/dkms/pivccu/1.0.36/build/make.log for more information.
Created symlink from /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service to /lib/systemd/system/pivccu-dkms.service.
Created symlink from /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service to /lib/systemd/system/pivccu-dkms.service.
Created symlink from /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service to /lib/systemd/system/pivccu-dkms.service.
Setting up raspberrypi-kernel-headers (1.20170703-1) ...
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.9.35+
Error! Bad return status for module build on kernel: 4.9.35+ (armv7l)
Consult /var/lib/dkms/pivccu/1.0.36/build/make.log for more information.
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.9.35-v7+
Error! Bad return status for module build on kernel: 4.9.35-v7+ (armv7l)
Consult /var/lib/dkms/pivccu/1.0.36/build/make.log for more information.
root@raspberrypi:~# 
```
Looking the make.log:
```
root@raspberrypi:/usr/src# more /var/lib/dkms/pivccu/1.0.36/build/make.log
DKMS make.log for pivccu-1.0.36 for kernel 4.9.35-v7+ (armv7l)
Sun 22 Sep 10:20:44 CEST 2019
make -C /lib/modules/4.9.35-v7+/build M=/var/lib/dkms/pivccu/1.0.36/build modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.35-v7+'
  CC [M]  /var/lib/dkms/pivccu/1.0.36/build/eq3_char_loop.o
  CC [M]  /var/lib/dkms/pivccu/1.0.36/build/plat_eq3ccu2.o
  CC [M]  /var/lib/dkms/pivccu/1.0.36/build/generic_raw_uart.o
/var/lib/dkms/pivccu/1.0.36/build/generic_raw_uart.c: In function ‘generic_raw_uart_get_gpio_pin_number’:
/var/lib/dkms/pivccu/1.0.36/build/generic_raw_uart.c:726:12: error: implicit declaration of function ‘dev_fwnode’ [-Werror=implicit-function-declaration]
     struct fwnode_handle *fwnode = dev_fwnode(dev);
            ^
/var/lib/dkms/pivccu/1.0.36/build/generic_raw_uart.c:726:36: warning: initialization makes pointer from integer without a cast
     struct fwnode_handle *fwnode = dev_fwnode(dev);
                                    ^
cc1: some warnings being treated as errors
scripts/Makefile.build:299: recipe for target '/var/lib/dkms/pivccu/1.0.36/build/generic_raw_uart.o' failed
make[2]: *** [/var/lib/dkms/pivccu/1.0.36/build/generic_raw_uart.o] Error 1
Makefile:1490: recipe for target '_module_/var/lib/dkms/pivccu/1.0.36/build' failed
make[1]: *** [_module_/var/lib/dkms/pivccu/1.0.36/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.9.35-v7+'
Makefile:23: recipe for target 'all' failed
make: *** [all] Error 2
```

I have the doubt that my kernel (4.9.35-v7+)  is not supported.
Can you please help with it?

**Comment by alexreinert** [comment]
You need at least kernel 4.14. This kernel is used in Raspbian Stretch and Buster. Maybe you have an old installation which has the Jessie kernel?

**Comment by zioalex** [comment]
Hi Alex, Ouch. Yes it is a Jessie Installation. Let me update to Stretch or Buster. Will update you soon.

**Comment by alexreinert** [comment]
Do you still have any questions or can this be closed?

**Comment by zioalex** [comment]
I am still updating to buster. The process is quite slow on the Raspberry
Pi.
Let me confirm that everything is working properly.

**Comment by zioalex** [comment]
Okay now I am able tp install everything but something is wrong.
```
piVCCU version: 2.47.15-53
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Not assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          RUNNING
PID:            3042
IP:             192.168.178.186
IP:             2003:d1:df0f:a6f1:a869:99ff:fe30:d31b
IP:             fd85:6fd0:5f94:1:a869:99ff:fe30:d31b
CPU use:        15.77 seconds
BlkIO use:      3.76 MiB
Memory use:     53.80 MiB
KMem use:       2.48 MiB
Link:           vethpivccu
 TX bytes:      7.35 KiB
 RX bytes:      73.54 KiB
 Total bytes:   80.89 KiB
```
When I access the CCU gui I get "ccuNotReady"
My module is not recognized.
```
Sep 26 16:16:22 raspberrypi.home.local systemd[1]: Starting piVCCU...
Sep 26 16:16:49 raspberrypi.home.local piVCCU[4042]: HMRF hardware was not detected
Sep 26 16:16:49 raspberrypi.home.local start_container.sh[3968]: <12>Sep 26 16:16:49 piVCCU: HMRF hardware was not detected
Sep 26 16:16:49 raspberrypi.home.local piVCCU[4043]: HMIP hardware was not detected
Sep 26 16:16:49 raspberrypi.home.local start_container.sh[3968]: <12>Sep 26 16:16:49 piVCCU: HMIP hardware was not detected
```

**Comment by zioalex** [comment]
I reinstalled a clean Buster installation and now everything works properly:
```
root@raspberrypi:~# pivccu-info 
piVCCU version: 2.47.15-53
Kernel modules: Available
Raw UART dev:   Available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  HM-MOD-RPI-PCB
HMIP Hardware:  HM-MOD-RPI-PCB
Board serial:   PEQ2215944
Radio MAC:      0x6bdd19
SGTIN:          3014F711A061A7D8A9AB3808
State:          RUNNING
PID:            2004
IP:             192.168.178.102
IP:             2003:d1:df0f:a6f1:389b:24ff:fe2d:df85
IP:             fd85:6fd0:5f94:1:389b:24ff:fe2d:df85
CPU use:        177.55 seconds
BlkIO use:      136.00 KiB
Memory use:     97.30 MiB
KMem use:       4.25 MiB
Link:           vethpivccu
 TX bytes:      23.54 MiB
 RX bytes:      4.79 MiB
 Total bytes:   28.33 MiB
```
Thanks Alex for the support.
