### ISSUE TITLE
pivccu-dkms fails to build with Linux 6.11

### ISSUE THREAD

**Issue by sbyx** [alexreinert/piVCCU#534]
Build log as follows:

```
In file included from /var/lib/dkms/pivccu/1.0.84/build/pl011_raw_uart.c:36:
/var/lib/dkms/pivccu/1.0.84/build/generic_raw_uart.h:136:17: error: initialization of 'void (*)(struct platform_device *)' from incompatible pointer type 'int (*)(struct platform_device *)' [-Werror=incompatible-pointer-types]
  136 |       .remove = __##__raw_uart_driver##_remove,
                \
      |                 ^~
/var/lib/dkms/pivccu/1.0.84/build/pl011_raw_uart.c:331:1: note: in expansion of macro 'module_raw_uart_driver'
  331 | module_raw_uart_driver(MODULE_NAME, pl011_raw_uart, pl011_raw_uart_of_match);
      | ^~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/pivccu/1.0.84/build/generic_raw_uart.h:136:17: note: (near initialization for '__raw_uart_driver_platform_driver.<anonymous>.remove')
  136 |       .remove = __##__raw_uart_driver##_remove,
                \
      |                 ^~
/var/lib/dkms/pivccu/1.0.84/build/pl011_raw_uart.c:331:1: note: in expansion of macro 'module_raw_uart_driver'
  331 | module_raw_uart_driver(MODULE_NAME, pl011_raw_uart, pl011_raw_uart_of_match);
      | ^~~~~~~~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/pivccu/1.0.84/build/dw_apb_raw_uart.o
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-6.11.5+bpo-common/scripts/Makefile.build:249: /var/lib/dkms/pivccu/1.0.84/build/pl011_raw_uart.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/var/lib/dkms/pivccu/1.0.84/build/generic_raw_uart.c:824:5: warning: no previous prototype for 'generic_raw_uart_get_gpio_index' [-Wmissing-prototypes]
  824 | int generic_raw_uart_get_gpio_index(struct device *dev, char *con_id, unsigned int idx)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/pivccu/1.0.84/build/generic_raw_uart.c:839:5: warning: no previous prototype for 'generic_raw_uart_get_led_gpio_index' [-Wmissing-prototypes]
  839 | int generic_raw_uart_get_led_gpio_index(struct generic_raw_uart_instance *instance, struct device *dev, enum generic_raw_uart_led led)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/pivccu/1.0.84/build/generic_raw_uart.c:971:5: warning: no previous prototype for 'generic_raw_uart_probe_rtc_device' [-Wmissing-prototypes]
  971 | int generic_raw_uart_probe_rtc_device(struct device *dev, bool *rtc_detected)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/pivccu/1.0.84/build/dw_apb_raw_uart.c:39:
/var/lib/dkms/pivccu/1.0.84/build/generic_raw_uart.h:136:17: error: initialization of 'void (*)(struct platform_device *)' from incompatible pointer type 'int (*)(struct platform_device *)' [-Werror=incompatible-pointer-types]
  136 |       .remove = __##__raw_uart_driver##_remove,
                \
      |                 ^~
/var/lib/dkms/pivccu/1.0.84/build/dw_apb_raw_uart.c:414:1: note: in expansion of macro 'module_raw_uart_driver'
  414 | module_raw_uart_driver(MODULE_NAME, dw_apb_raw_uart, dw_apb_raw_uart_of_match);
      | ^~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/pivccu/1.0.84/build/generic_raw_uart.h:136:17: note: (near initialization for '__raw_uart_driver_platform_driver.<anonymous>.remove')
  136 |       .remove = __##__raw_uart_driver##_remove,
                \
      |                 ^~
/var/lib/dkms/pivccu/1.0.84/build/dw_apb_raw_uart.c:414:1: note: in expansion of macro 'module_raw_uart_driver'
  414 | module_raw_uart_driver(MODULE_NAME, dw_apb_raw_uart, dw_apb_raw_uart_of_match);
      | ^~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
```

**Comment by sbyx** [comment]
Sorry, just saw #533 should fix this.
