### ISSUE TITLE
Compilierung der Kernelmodule schlägt fehl unter armbian jammy (5.17.1 kernel) auf odroid c2

### ISSUE THREAD

**Issue by jagiella** [alexreinert/piVCCU#436]
Seit dem letzten kernel update funktioniert das Compilieren der Kernelmodule leider nicht mehr:
- Installation von `pivccu-modules-dkms`:
```bash
$ sudo dpkg-reconfigure pivccu-modules-dkms
Removed /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service.
Removed /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service.
Removed /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service.
Deleting module pivccu-1.0.71 completely from the DKMS tree.
Error! The module/version combo: pivccu-1.0.71 is not located in the DKMS tree.
Creating symlink /var/lib/dkms/pivccu/1.0.71/source -> /usr/src/pivccu-1.0.71

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.17.1-meson64 ARCH=arm64 all.......(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.17.1-meson64 (aarch64)
Consult /var/lib/dkms/pivccu/1.0.71/build/make.log for more information.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Unit /lib/systemd/system/pivccu-dkms.service is added as a dependency to a non-existent unit debmatic.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
```

- `/var/lib/dkms/pivccu/1.0.71/build/make.log`:
```bash
DKMS make.log for pivccu-1.0.71 for kernel 5.17.1-meson64 (aarch64)
Sa 30. Apr 18:17:02 CEST 2022
make -C /lib/modules/5.17.1-meson64/build M=/var/lib/dkms/pivccu/1.0.71/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.17.1-meson64'
  CC [M]  /var/lib/dkms/pivccu/1.0.71/build/eq3_char_loop.o
  CC [M]  /var/lib/dkms/pivccu/1.0.71/build/plat_eq3ccu2.o
  CC [M]  /var/lib/dkms/pivccu/1.0.71/build/generic_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.71/build/pl011_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.71/build/dw_apb_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.71/build/meson_raw_uart.o
/var/lib/dkms/pivccu/1.0.71/build/generic_raw_uart.c: In function ‘generic_raw_uart_proc_open’:
/var/lib/dkms/pivccu/1.0.71/build/generic_raw_uart.c:776:48: error: implicit declaration of function ‘PDE_DATA’; did you mean ‘NODE_DATA’? [-Werror=implicit-function-declaration]
  776 |   struct generic_raw_uart_instance *instance = PDE_DATA(inode);
      |                                                ^~~~~~~~
      |                                                NODE_DATA
/var/lib/dkms/pivccu/1.0.71/build/generic_raw_uart.c:776:48: warning: initialization of ‘struct generic_raw_uart_instance *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
/var/lib/dkms/pivccu/1.0.71/build/dw_apb_raw_uart.c: In function ‘dw_apb_raw_uart_irq_handle’:
/var/lib/dkms/pivccu/1.0.71/build/dw_apb_raw_uart.c:259:8: warning: this statement may fall through [-Wimplicit-fallthrough=]
  259 |     if (!(status & (UART_LSR_DR | UART_LSR_BI)))
      |        ^
/var/lib/dkms/pivccu/1.0.71/build/dw_apb_raw_uart.c:265:3: note: here
  265 |   case UART_IIR_RDI:
      |   ^~~~
  CC [M]  /var/lib/dkms/pivccu/1.0.71/build/fake_hmrf.o
  CC [M]  /var/lib/dkms/pivccu/1.0.71/build/rpi_rf_mod_led.o
  CC [M]  /var/lib/dkms/pivccu/1.0.71/build/dummy_rx8130.o
  CC [M]  /var/lib/dkms/pivccu/1.0.71/build/led_trigger_timer.o
  CC [M]  /var/lib/dkms/pivccu/1.0.71/build/hb_rf_usb.o
cc1: some warnings being treated as errors
/var/lib/dkms/pivccu/1.0.71/build/fake_hmrf.c: In function ‘fake_hmrf_write’:
/var/lib/dkms/pivccu/1.0.71/build/fake_hmrf.c:268:1: warning: the frame size of 2080 bytes is larger than 1024 bytes [-Wframe-larger-than=]
  268 | }
      | ^
make[2]: *** [scripts/Makefile.build:288: /var/lib/dkms/pivccu/1.0.71/build/generic_raw_uart.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1831: /var/lib/dkms/pivccu/1.0.71/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.17.1-meson64'
make: *** [Makefile:30: all] Error 2
```
- system:
```bash
$ uname -a
Linux odroidc2 5.17.1-meson64 #trunk.0038 SMP PREEMPT Thu Apr 7 14:56:23 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

$ apt list --installed linux*
Auflistung… Fertig
linux-base/jammy,jammy,now 4.5ubuntu9 all  [installiert]
linux-dtb-edge-meson64/jammy,now 22.05.0-trunk.0038 arm64  [installiert]
linux-headers-edge-meson64/jammy,now 22.05.0-trunk.0038 arm64  [installiert]
linux-image-edge-meson64/jammy,now 22.05.0-trunk.0038 arm64  [installiert]
linux-libc-dev/jammy,now 22.02.1 arm64  [Installiert,automatisch]
linux-u-boot-odroidc2-edge/jammy,now 22.02.1 arm64  [installiert]

$ apt list --installed pivccu*
Auflistung… Fertig
pivccu-devicetree-armbian/testing,testing,now 1.0.34 all  [installiert]
pivccu-modules-dkms/testing,testing,now 1.0.71 all  [installiert]
pivccu3/testing,now 3.63.8-70 arm64  [installiert]
```

**Comment by jagiella** [comment]
Ein möglicher Fix könnte sich hier inspirieren:
https://github.com/NixOS/nixpkgs/pull/166232/files
