### ISSUE TITLE
Asus TinkerBoard S; armbian Kernel 5.8.6-rockchip

### ISSUE THREAD

**Issue by schmimat** [alexreinert/piVCCU#286]
Hallo,

vielen Dank erstmal für deine tolle Entwicklung.

Habe gerade bei meinem Asus TinkerBoard S auf den Kernel 5.8.6-rockchip upgedatet.
Nun bricht die Compilierung von _pivccu-modules-dkms_ mit folgender Fehlermeldung ab:

    make -j4 KERNELRELEASE=5.8.6-rockchip ARCH=arm all....(bad exit status: 2)
    Error! Bad return status for module build on kernel: 5.8.6-rockchip (armv7l)
    Consult /var/lib/dkms/pivccu/1.0.42/build/make.log for more information.

Hier noch die `/var/lib/dkms/pivccu/1.0.42/build/make.log`

    DKMS make.log for pivccu-1.0.42 for kernel 5.8.6-rockchip (armv7l)
    Mi 9. Sep 12:51:25 CEST 2020
    make -C /lib/modules/5.8.6-rockchip/build M=/var/lib/dkms/pivccu/1.0.42/build modules
    make[1]: Verzeichnis „/usr/src/linux-headers-5.8.6-rockchip“ wird betreten
      CC [M]  /var/lib/dkms/pivccu/1.0.42/build/eq3_char_loop.o
      CC [M]  /var/lib/dkms/pivccu/1.0.42/build/plat_eq3ccu2.o
      CC [M]  /var/lib/dkms/pivccu/1.0.42/build/generic_raw_uart.o
      CC [M]  /var/lib/dkms/pivccu/1.0.42/build/pl011_raw_uart.o
      CC [M]  /var/lib/dkms/pivccu/1.0.42/build/dw_apb_raw_uart.o
    /var/lib/dkms/pivccu/1.0.42/build/generic_raw_uart.c: In function ‘generic_raw_uart_probe’:
    /var/lib/dkms/pivccu/1.0.42/build/generic_raw_uart.c:901:57: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
       proc_create_data(dev_name(instance->dev), 0444, NULL, &generic_raw_uart_proc_fops, instance);
                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /var/lib/dkms/pivccu/1.0.42/build/generic_raw_uart.c:32:
    ./include/linux/proc_fs.h:102:31: note: expected ‘const struct proc_ops *’ but argument is of type ‘const struct file_operations *’
     extern struct proc_dir_entry *proc_create_data(const char *, umode_t,
                                   ^~~~~~~~~~~~~~~~
    At top level:
    /var/lib/dkms/pivccu/1.0.42/build/generic_raw_uart.c:146:13: warning: ‘generic_raw_uart_is_connected’ defined but not used [- Wunused-function]
     static bool generic_raw_uart_is_connected(struct generic_raw_uart_instance *instance)
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      CC [M]  /var/lib/dkms/pivccu/1.0.42/build/meson_raw_uart.o
    /var/lib/dkms/pivccu/1.0.42/build/dw_apb_raw_uart.c: In function ‘dw_apb_raw_uart_irq_handle’:
    /var/lib/dkms/pivccu/1.0.42/build/dw_apb_raw_uart.c:257:8: warning: this statement may fall through [-Wimplicit-fallthrough=]
         if (!(status & (UART_LSR_DR | UART_LSR_BI)))
            ^
    /var/lib/dkms/pivccu/1.0.42/build/dw_apb_raw_uart.c:263:3: note: here
       case UART_IIR_RDI:
       ^~~~
      CC [M]  /var/lib/dkms/pivccu/1.0.42/build/fake_hmrf.o
    cc1: some warnings being treated as errors
    make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/pivccu/1.0.42/build/generic_raw_uart.o] Fehler 1
    make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
    /var/lib/dkms/pivccu/1.0.42/build/fake_hmrf.c: In function ‘fake_hmrf_write’:
    /var/lib/dkms/pivccu/1.0.42/build/fake_hmrf.c:266:1: warning: the frame size of 2064 bytes is larger than 1024 bytes [-Wframe-larger-than=]
     }
     ^
    make[1]: *** [Makefile:1756: /var/lib/dkms/pivccu/1.0.42/build] Fehler 2
    make[1]: Verzeichnis „/usr/src/linux-headers-5.8.6-rockchip“ wird verlassen
    make: *** [Makefile:25: all] Fehler 2

Mit dem Kernel 5.4.44-rockchip (armbian 20.05.2) ist alles in bester Ordnung.

Vielen Dank für deine Bemühungen

mfG Matthias

**Comment by Harpau** [comment]
Genau das selbe Problem habe ich ebenfalls beim Versuch piVCCU3 auf meinem neuen TinkerBoard S zu installieren.

Vielen Dank und viele Grüße

Harald

**Comment by alexreinert** [comment]
Ich habe im testing APT Repo ein aktualisiertes Paket bereitgestellt, welches auch unter Kernel 5.8 läuft.

**Comment by schmimat** [comment]
Das aktualisierte Packet funktioniert auch mit dem Kernel 5.8.

Vielen Dank.

mfG Matthias

**Comment by schmimat** [comment]
Das aktualisierte Packet funktioniert auch mit dem Kernel 5.8.

Vielen Dank.

mfG Matthias

**Comment by Harpau** [comment]
Hallo Alex, bei mir läuft es nun ebenfalls mit der aktuellen Version von armbian.com. Vielen Dank für Deine tolle Entwicklung und die ausgezeichnete Unterstützung! Harald

**Comment by v0r73x** [comment]
Hi Zusammen,

ich bekomme noch immer den Fehler ?! Habe ich etwas falsch gemacht ?
![image](https://user-images.githubusercontent.com/48632087/95733091-eb202900-0c81-11eb-83df-633fd08927f2.png)

**Comment by alexreinert** [comment]
Was stehe in der im Screenshot angegeben make.log?
