### ISSUE TITLE
Nach Raspi Update will pivccu nicht mehr (ccu2)

### ISSUE THREAD

**Issue by Homezecke** [alexreinert/piVCCU#504]
Hallo, ich habe ein ähnliches Problem wie hier #484 . Ich hatte auch versehentlich da gepostet. Zu spät gesehen dass schon auf closed.

Also bei mir genauso. Raspi geupdatet, danach kein pivccu mehr. Das Ändern der config mit rausnahme von 64 Bit lässt auch mein System nicht starten. Es kann aber eigentlich auch gar nicht daran liegen. Ich habe mir nämlich ein zweites identisches image (ohne Raspi update) angelegt da ist 64 Bit berits aktiv, und piVCCU funktioniert da ja trotzdem. Allerdings muss ich dazu noch erwähnen, dass ich noch ccu2 benutze.

Welche pakete sollte ich durch hold vom update ausschließen, damit pivccu auf altem Stand bleibt?

**Comment by alexreinert** [comment]
Die CCU2 Version ist schon weit über ein Jahr Out-of-Service.
Poste bitte mal die Ausgabe von pivccu-info, vielleicht kann ich was erkennen, aber es kann auch sein, dass die Kernel Module mittlerweile einfach nicht mehr kompatibel sind.

**Comment by Homezecke** [comment]
piVCCU version: 2.61.7-69
Kernel modules: Not available
Raw UART dev:   Not available
Rasp.Pi UART:   Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown
State:          STOPPED

Ich denke auch, dass es nicht mehr kompatibel ist. Ich denke, sobald ich auf bookworm wechsle gehe ich dann auch auf ccu3...

**Comment by Homezecke** [comment]
Removed /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service.
Removed /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service.
Removed /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service.

------------------------------
Deleting module version: 1.0.68
completely from the DKMS tree.
------------------------------
Done.
Error! The module/version combo: pivccu-1.0.68
is not located in the DKMS tree.

Creating symlink /var/lib/dkms/pivccu/1.0.68/source ->
                 /usr/src/pivccu-1.0.68

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...(bad exit status: 2)
make -j4 KERNELRELEASE=6.1.21-v8+ ARCH=arm64 all........(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.1.21-v8+ (aarch64)
Consult /var/lib/dkms/pivccu/1.0.68/build/make.log for more information.
Created symlink /etc/systemd/system/multi-user.target.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/debmatic.service.wants/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.
Created symlink /etc/systemd/system/pivccu.service.requires/pivccu-dkms.service → /lib/systemd/system/pivccu-dkms.service.

**Comment by Homezecke** [comment]
und noch das make.log:

DKMS make.log for pivccu-1.0.68 for kernel 6.1.21-v8+ (aarch64)
Fri 15 Sep 10:28:47 CEST 2023
make -C /lib/modules/6.1.21-v8+/build M=/var/lib/dkms/pivccu/1.0.68/build modules
make[1]: Entering directory '/usr/src/linux-headers-6.1.21-v8+'
  CC [M]  /var/lib/dkms/pivccu/1.0.68/build/eq3_char_loop.o
  CC [M]  /var/lib/dkms/pivccu/1.0.68/build/plat_eq3ccu2.o
  CC [M]  /var/lib/dkms/pivccu/1.0.68/build/generic_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.68/build/pl011_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.68/build/dw_apb_raw_uart.o
  CC [M]  /var/lib/dkms/pivccu/1.0.68/build/meson_raw_uart.o
/var/lib/dkms/pivccu/1.0.68/build/generic_raw_uart.c: In function ‘generic_raw_uart_proc_open’:
/var/lib/dkms/pivccu/1.0.68/build/generic_raw_uart.c:742:48: error: implicit declaration of function ‘PDE_DATA’; did you mean ‘NODE_DA>
  742 |   struct generic_raw_uart_instance *instance = PDE_DATA(inode);
      |                                                ^~~~~~~~
      |                                                NODE_DATA
/var/lib/dkms/pivccu/1.0.68/build/generic_raw_uart.c:742:48: warning: initialization of ‘struct generic_raw_uart_instance *’ from ‘int>
/var/lib/dkms/pivccu/1.0.68/build/generic_raw_uart.c: In function ‘generic_raw_uart_get_gpio_pin_number’:
/var/lib/dkms/pivccu/1.0.68/build/generic_raw_uart.c:774:31: error: implicit declaration of function ‘fwnode_get_named_gpiod’; did you>
  774 |     struct gpio_desc *gpiod = fwnode_get_named_gpiod(fwnode, label, 0, GPIOD_ASIS, label);
      |                               ^~~~~~~~~~~~~~~~~~~~~~
      |                               fwnode_get_named_child_node
/var/lib/dkms/pivccu/1.0.68/build/generic_raw_uart.c:774:31: warning: initialization of ‘struct gpio_desc *’ from ‘int’ makes pointer >
  CC [M]  /var/lib/dkms/pivccu/1.0.68/build/fake_hmrf.o
/var/lib/dkms/pivccu/1.0.68/build/dw_apb_raw_uart.c: In function ‘dw_apb_raw_uart_irq_handle’:
/var/lib/dkms/pivccu/1.0.68/build/dw_apb_raw_uart.c:259:8: warning: this statement may fall through [-Wimplicit-fallthrough=]
  259 |     if (!(status & (UART_LSR_DR | UART_LSR_BI)))
      |        ^
/var/lib/dkms/pivccu/1.0.68/build/dw_apb_raw_uart.c:265:3: note: here
  265 |   case UART_IIR_RDI:
      |   ^~~~
  CC [M]  /var/lib/dkms/pivccu/1.0.68/build/rpi_rf_mod_led.o
  CC [M]  /var/lib/dkms/pivccu/1.0.68/build/dummy_rx8130.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/pivccu/1.0.68/build/generic_raw_uart.o] Error 1

**Comment by alexreinert** [comment]
Das Log zeigt leider eindeutig, dass die alte Version vom Kernel Module nicht mehr mit deinem Kernel kompatibel ist. Die neueste Version vom Kernel Module wäre damit kompatibel, allerdings ist diese nicht mit der CCU2 Version von piVCCU kompatibel.

**Comment by alexreinert** [comment]
Ich sehe daher nur zwei Möglichkeiten: Downgrade des Kernels oder Wechsel auf die CCU3 Version.

**Comment by Homezecke** [comment]
Ok, wie gesagt werde dann auch zu ccu3 wechseln. Macht keinen Sinn mehr.

Danke für Deine Bemühungen!
